### PR TITLE
fix var hides class member, this-> in constructors

### PR DESCRIPTION
**Pull request by diablodale**
- fix few compile warn 'ex' unreferenced local variable
- rename setBusId() param to not hide class member
- partial fix luxonis/depthai-core#247

### CODE REVIEW

**Review by themarpe — CHANGES_REQUESTED** [review]
Thanks - 2 things
 - Use different naming than prepended with `_` 
 - & would make sense to add the flags for this to CI, as we don't work with such high warnings, and codebase will "derail" again. 

Though I see these as style more so than "issues"

**Comment by diablodale** [comment]
I will make other names that with `_`.

I don't understand what you want me to do with "& would make sense to add the flags for this to CI". 🤷‍♀️

There are bugs in depthai-core like all code. Some of those bugs the compiler has identified but your team doesn't get the reports because more warnings (like /W4 with MSVC) are not enabled. When /W4 is enabled, there is a lot lot lot. Some are true bugs like I reported at #766. Others are style. But there are so many...it is difficult to separate bugs from style. Therefore, reducing style issues allows for bugs to be more easily seen. That is my intention.

**Comment by themarpe** [comment]
> I will make other names that with _.

Thanks

> Therefore, reducing style issues allows for bugs to be more easily seen. That is my intention

Got it - lets keep it this way for now, and see how for we get to a full /W4 clean build

**Comment by diablodale** [comment]
forcepushed

* removed the `_` names
* slight refactor of XLinkConnection to fix clang-tidy warn of "use initializers" and "initializer should not duplicate what is already the default initializer in the class header".

> Got it - lets keep it this way for now, and see how for we get to a full /W4 clean build

Fixing issues in depthai headers tends to be my personal priority because those issues surface and break my build when I compile my own apps with `/W4`. This PR is progress...a step along the path towards a clean /W4 build.

I don't recommend /W4 for release/retail builds. In contrast, I do recommend that all new code should pass with no /W4 warns. New code is checked before adding, developer skill/style/technique improves, and the codebase continues on a path of less and less warns. Enforcing this on push is something your github+CI setup would need to enforce on push and/or pr merge. That's a topic/process that is completely within your team's purview. I can only recommend.

**Review by themarpe — APPROVED** [review]

**Pull request merged**
