### PR TITLE
DataInputQueue nullptr check

### PR DESCRIPTION
**Pull request by themarpe**
This checks if a nullptr was passed to `send` method of DataInputQueue and which also applies to `None` being passed from Python bindings

### CODE REVIEW

**Review by szabi-luxonis — APPROVED** [review]
LGTM.
Is there a context where this issue came up (out of curiosity) or just general fix?

**Comment by Luxonis-Brandon** [comment]
I was just about to ask the same question actually.  Mainly because I'm overly-optimistically-hoping that this is the fix to Raspberry Pi issue.  But I'm guessing this is likely not the resolution to that but rather something discovered in that hunt.

**Comment by themarpe** [comment]
Unfortunately doesn't addresses any burning issue - was a tad stale from a couple of days ago as I was working on a custom script and sent `None` type instead of actual message (returned by a "void" function in Python). Programming mistake on my end but looked quite serious at first glance.

**Comment by Luxonis-Brandon** [comment]
Thanks.  Makes sense.

**Pull request merged**
