### PR TITLE
fix narrowing compile warnings; mutex lock

### PR DESCRIPTION
**Pull request by diablodale**
Partially fixes https://github.com/luxonis/depthai-core/issues/71

The PR does not include the unsafe function usage (e.g. strncpy) that @themarpe wrote they want to resolve. I see opportunities to move away from unsafe c-strings. Alternatives are string spans, zstring, std::string, std::array, etc. I highly recommend moving away from c-strings; buffer/string handling is one of the most common security vulnerabilities and I believe the current thinking is any performance gain from raw c-strings are no longer relevant. http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#slstr-string

The changes in this PR are usually the smallest changes needed to compile without warnings using this project's cmake. There is unsafe code and I do not address that in this PR. For example, in bspatch.c lines 129,134 -or- DeviceBootloader.cpp lines 101,102,107,... are warnings of narrowing integers (int64_t->unsigned int, size_t->uint32_t, etc.) This are all possible loss/corrupt of data, loss of precision, etc. The changes I made remove the compile warnings. However, the problems causing the warning still exist. It is still possible to overflow, wraparound, loose precision, etc. To fix the underlying problem requires work that cascades wider. I'm confident these underlying issues are fixable, but outside the scope of this PR without further discussion. This means that the code is often just as "unsafe" as it was before. If you want to fix all these, we should discuss enough examples so that I understand your project's philosophy and can apply wider fixes.

I did not add/use GSL. I think it might be useful in your project, but I chose to use other methods to fix for now.

I did not fix warnings in the hunter managed FP16 project.,

I have a question. I have not fixed the cmake warning in CMakeLists.txt line 30 `set(DEPTHAI_VERSION ${PROJECT_VERSION} PARENT_SCOPE)`. The warning is `CMake Warning (dev) at CMakeLists.txt:30 (set):Cannot set "DEPTHAI_VERSION": current scope has no parent.` My question is...what is the goal with that set(DEPTHAI_VERSION)? If it is for this project to declare its version, then this is not the cmake way to do it. Instead, creating a version config file is relatively easing using the helper functions https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html and that version config file will set variables that can be read in a consistent way, uses in package version checks, etc. What is your project's intention here?

Device.cpp line 401. I added a variable name for the lock. This means...the previous code *did not* lock the mutex. Technically it locked it for only line 401 as the lock was created and destroyed on that one line. 🎯This looks like important critical path code so locking the mutex where it was never locked before is exposing bugs elsewhere as I document in issue #79.

I see a lot of int<->float conversions for framerate in VideoEncoder.cpp. Seems like something could be unified. For example: `VideoEncoder::setDefaultProfilePreset(float fps)`, calls `setFrameRate(int fps)`, which sets `float dai::VideoEncoderProperties::frameRate`. float->int->float has multiple layers of precision loss and unneeded cpu cycles.

### CODE REVIEW

**Comment by themarpe** [comment]
Thanks for the PR.

The C-style strings are used only for compatibility with third party XLink library - which we decided not to modify too much for now.

 Most conversions from 64bit to 32bit arise from the fact that the target is a 32bit processor, so we settled with those datasizes.
 
 ```
 set(DEPTHAI_VERSION ${PROJECT_VERSION} PARENT_SCOPE)
```
Intention of the above is to present the version to the *parent* project (in our case, `depthai-python`), which adds it as a subdirectoy without the need to either parse the `CMakeLists.txt` or to install.

Thanks for catching that `unique_lock` issue. Lets hold off until further, to see the implications of it and to fix any subsequent issues that it triggers.

Can you modify the `setFrameRate` to take an float instead in the same PR? Just a mistake there.

Seems like `style` is failing. Did you run `cmake --build [dir] --target clangformat` to apply style?

**Comment by diablodale** [comment]
I'll try and reconcile the framerates together.

Having difficulty with style. The logs in the CI don't tell me what failed. Just...bad. It would be great if the CI presented the output of the check so that I an told the specific problem, can learn from it, and can make specific changes. I'm on Windows and vscode, the setup of clangformat and such is foreign to that. So I'm trying to get something to tell me anything. So far, no luck.

Ehh, the add_subdirectory rather than the full config and version loading is a bit hacky but if it work for you...I'll leave it alone. It's your team's choice and I will generally stay far away from python. So the error in cmakefile.tx due to python I will not fix.

**Comment by diablodale** [comment]
clangeformat updated...seems the tool, by default, doesn't tell of problems/errors...it just blindly makes changes. 🤷‍♀️

I made framerate round-trip a float.

**Comment by diablodale** [comment]
squashed

**Comment by diablodale** [comment]
@themarpe, can we merge in this PR? Its becoming out of sync due to delayed merge.

**Comment by themarpe** [comment]
@diablodale thanks, merged.

Only exception was the mutex part - I've commented that out for now and marked it `TODO` until we figure out the Windows issue.

**Pull request merged**
