### PR TITLE
fix Win MSVC cmake INTERPROCEDURAL_OPTIMIZATION

### PR DESCRIPTION
**Pull request by diablodale**
Workaround for Windows MSVC incompatibility with BUILD_SHARED_LIBS + WINDOWS_EXPORT_ALL_SYMBOLS + INTERPROCEDURAL_OPTIMIZATION
Fixes luxonis/depthai-core#334

Approach:  used the existing `add_default_flags()` function as the issue is about flags and that function was used in all the needed places.

I'm interested to see the CI test it across the matrix. 🤔
Passes all tests and examples on my Windows MSVC x64 build, debug+release, with settings...
```cmake
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON CACHE BOOL "")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_DEBUG OFF CACHE BOOL "")
```

### CODE REVIEW

**Comment by diablodale** [comment]
These seem to be valid bugs surfaced in the tests and examples. The comprehensive fix is to fix the code in the tests+examples.
A workaround is to ignore those bugs and not apply the default flags to them which are currently surfacing valid issues.

Opinions? Thoughts?

**Comment by themarpe** [comment]
@diablodale 
```
/home/runner/work/depthai-core/depthai-core/tests/src/bootloader_config_test.cpp:23:22: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::array<unsigned char, 4>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
   23 |     for(int i = 0; i < ipv4InMemory.size(); i++) {
      |                    ~~^~~~~~~~~~~~~~~~~~~~~
```

Can you fix the surfaced issues in the scope of this PR as well? Not sure if this is the only one, but seems minor.

**Comment by diablodale** [comment]
> Can you fix the surfaced issues in the scope of this PR as well? Not sure if this is the only one, but seems minor.

I have the knowledge, though want to be careful with my time the next two weeks as I am in release crunch.
I do not have a Linux build harness setup. And I don't know if those Linux flags are/will report errors in depthai-core itself (not tests/examples)...how deep goes the rabbit hole🐇😆?

Does anyone on your team have a ready-made Dockerfile for building on Ubuntu? That can help speed my progress. If not, I'll need to make one today.

**Comment by themarpe** [comment]
Thanks - as your time permits

> Does anyone on your team have a ready-made Dockerfile for building on Ubuntu? That can help speed my progress. If not, I'll need to make one today.

We have from `depthai-python`, but rechecked, it doesn't include native opencv deps which would be needed for examples...

I'll test locally if that change is the only one and circle back.

**Comment by themarpe** [comment]
Using default flags on examples pops up way to many warnings & errors. 

I think it would be better for sake of simplicity of examples to not have those flags set to such high levels.

**Comment by diablodale** [comment]
I suspected 🐛🦶.
Are you seeing the error/warns from the SDK code, or are they only errors/warns in the cpp files of the tests+examples?
If the former...yes...there is sdk cleanup work to do ;-)
If the latter...it couldn't be more than a long day work; two max? There are only ~65 cpp files for tests+examples.

If not fix the errant code, then I could move this PR's fix out of `add_default_flags()` to something separate. Or add a param like `add_default_flags(BUGS_ONLY)` or `add_default_flags(FIXES_ONLY)`. Or...?

**Comment by themarpe** [comment]
More the latter - but given the set of flags, it'd make the examples more obstructed than necessary (making portraying the actual point harder).

I lean towards leaving out the flags for it, and only applying the MSVC flags to resolve the mentioned issue.
Lets move it out to a specific function or as mentioned adding a parameter to go along to only deal with this kind of flags - latter sounds nice, if there is going to be more of this kinds of things to handle...

**Comment by diablodale** [comment]
Would you start the CI again to test new changes?
I made a docker harness and fixed the test and example errors. Those are in the second commit.

I get no errors on my Ubuntu 20.04 docker. Limited in my ability to run tests without docker hardware access.
Windows compiled and tested good.

Warnings are still there like all main apps linking to depthai experience.

**Comment by diablodale** [comment]
Oy. One more time on the CI please.
I learned that gcc didn't support all the declared switches. So now I can also compile with clang13 and made the one fix. 🙄😂

**Comment by themarpe** [comment]
Sorry for the delay - I'd just modify that examples don't get all the flags, but just the ones required for the fix - to not spam with warnings in examples. Maybe `add_default_flags(target [LEAN/...])` with additional optional parameter or a separate function that only adds required flags

Otherwise LGTM

**Comment by diablodale** [comment]
Would you start CI?
I force pushed update that enables the optional flag idea as `add_default_flags(target [LEAN])` and updated test+example cmake's to use `LEAN`

**Pull request merged**
