### PR TITLE
Allow recursive-clone with forks

### PR DESCRIPTION
**Pull request by kunaltyagi**
Currently, forking private forks is an issue since the gitmodule path only moves 1 up the hierarchy.

This PR applies the change to main branch. If accepted, I'll create a similar PR for the gen2_develop branch

### CODE REVIEW

**Comment by Luxonis-Brandon** [comment]
This seems like a great idea.  Thank you!  Bringing up to team and likely will see an answer tomorrow when the team is back online.

**Comment by themarpe** [comment]
Seems like the solution to https://github.com/luxonis/depthai-core/pull/27#issuecomment-735962837 as well.
CC: @szabi-luxonis 

Any known drawbacks of this method @kunaltyagi?

**Comment by kunaltyagi** [comment]
None on github (at least that I know of). On gitlab, it might be an issue since the hierarchies can be arbitrary deep there

**Review by szabi-luxonis — APPROVED** [review]
LGTM

**Pull request merged**
